type Side = number;

let SIDE_PLAYER: Side = 1;
let SIDE_MONSTER: Side = 2;
let SIDE_NEUTRAL: Side = 3;
let SIDE_COLLECT: Side = 4;

let ALL_SIDES = [SIDE_PLAYER, SIDE_MONSTER, SIDE_NEUTRAL, SIDE_COLLECT];